project_setup <- function() {
  dir.create("data")
  file.create("data/README.md")
  writeLines("The data directory serves as a repository for all data used in this code.", "data/README.md")
  dir.create("paper")
  file.create("paper/README.md")
  writeLines("The paper directory serves as a repository for the manuscript.", "paper/README.md")
  dir.create("figs")
  file.create("figs/README.md")
  writeLines("The figs directory serves as a repository for all figures produced using this code.", "figs/README.md")
  dir.create("output")
  file.create("output/README.md")
  writeLines("The output directory contains any type of intermediate or output files (e.g. simulation outputs, models, processed datasets, etc.).", "output/README.md")
  dir.create("R")
  file.create("R/README.md")
  writeLines("The R directory contains all R scripts with function definitions.", "R/README.md")
  dir.create("reports")
  file.create("reports/README.md")
  writeLines("The reports directory contains Quarto documents that describe analysis and report results.", "reports/README.md")
  dir.create("docs")
  file.create("docs/README.md")
  writeLines("The docs directory contains rendered version of reports.", "data/README.md")
  dir.create("scratch")
  file.create("scratch/README.md")
  writeLines("The scratch directory contains prototypes and codes I do not fully understand yet.", "scratch/README.md")
  return("SUCCESS!")
}
